### ISSUE TITLE
Cloudbleed - More websites

### ISSUE THREAD

**Issue by tyteen4a03** [Dorian/doma#2]
Taviso has listed a few more websites in this HN comment: https://news.ycombinator.com/item?id=13727279

**Comment by Dorian** [comment]
@tyteen4a03 So, what I'm listing are the domains the data leaked from from not the ones that contain leaked data (e.g. Uber not Google cache). But thanks, I need to do some Bing scrapping now :)

**Comment by Dorian** [comment]
@tyteen4a03 Not sure what's going on on those pages, the only thing I recognized is a websocket connection to `gateway.discord.gg` which is already in the list.

**Comment by Dorian** [comment]
Some more research didn't give me anything interesting

> Some IPv6 internal connections, some websocket connections to gateway.discord.gg, rewrite rules for fruityfifty.com's AMP pages, and some internal domain `prox96.39.187.9cf-connecting-ip.com`.

> And some sketchy internal variables: `log_only_china`, `http_not_in_china`, `baidu_dns_test`, and `better_tor`.

https://news.ycombinator.com/item?id=13729797
